[platformio]
src_dir = .
include_dir = .
default_envs = release

[env:release]
platform = ststm32
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = genericSTM32C092xC
board_build.ldscript = STM32C092XX_FLASH.ld

;   mode=Normal : hotplug connect (no NRST needed).
;   mode=UR     : connect under reset (needs NRST wired) - use this if a
;                 Normal connect fails or to recover a misbehaving target.
upload_protocol = custom
upload_command = STM32_Programmer_CLI -c port=SWD mode=Normal -d "$BUILD_DIR/firmware.elf" -v -rst

extra_scripts = pre:scripts/build_script.py

build_src_filter =
    +<Core/Src/>
    +<Drivers/STM32C0xx_HAL_Driver/Src/>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
	+<Core/Src/pedals/>
    +<*.s>
build_flags = 
    -DUSE_HAL_DRIVER
	-std=gnu23
    -DSTM32C092xx
    -ICore/Inc
	-ICore/Inc/pedals/bots
	-ICore/Inc/pedals/brake
	-ICore/Inc/pedals/can-communication
	-ICore/Inc/pedals/fsm
	-ICore/Inc/pedals/identity
	-ICore/Inc/pedals/post
	-ICore/Inc/pedals/throttle
    -IDrivers/CMSIS/Include
    -IDrivers/STM32C0xx_HAL_Driver/Inc
    -IDrivers/STM32C0xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include

lib_deps =
    https://github.com/eagletrt/libcan-sw.git#master
	https://github.com/eagletrt/libpal-sw.git#v0.1.0
	https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
    clangtidy: --extra-arg=-std=gnu23
    clangtidy: --extra-arg=-U__cplusplus
check_src_filters =
    -<**>
    +<Core/Src/pedals>
    +<Core/Inc/pedals>


[env:tests]
platform = native
test_framework = unity
test_build_src = true

lib_deps = 
	https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
	https://github.com/eagletrt/libpal-sw.git#v0.1.0
	https://github.com/eagletrt/libcan-sw.git#master

build_flags =
	-std=gnu23
	-ICore/Inc/pedals/bots
	-ICore/Inc/pedals/brake
	-ICore/Inc/pedals/can-communication
	-ICore/Inc/pedals/fsm
	-ICore/Inc/pedals/identity
	-ICore/Inc/pedals/post
	-ICore/Inc/pedals/throttle
	-Itest/include
	-DEAGLETRT_STATIC=
	-lm

build_src_filter =
	-<**>
	+<Core/Src/pedals/>
	-<**/*.cpp>
	-<**/*.hpp>

[env:bootloader]
platform = ststm32
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = genericSTM32C092xC
board_build.ldscript = STM32C092XX_FLASH.ld

upload_protocol = custom
upload_command = STM32_Programmer_CLI -c port=SWD mode=Normal -d "$BUILD_DIR/firmware.elf" -v -rst

build_src_filter = 
	+<pedals-module-bootloader-sw/Core/Src/>
    +<pedals-module-bootloader-sw/Drivers/STM32C0xx_HAL_Driver/Src/>
    -<pedals-module-bootloader-sw/Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
    +<*.s>

build_flags = 
    -DUSE_HAL_DRIVER
    -DSTM32C092xx
    -Ipedals-module-bootloader-sw/Core/Inc
    -Ipedals-module-bootloader-sw/Drivers/CMSIS/Include
    -Ipedals-module-bootloader-sw/Drivers/STM32C0xx_HAL_Driver/Inc
    -Ipedals-module-bootloader-sw/Drivers/STM32C0xx_HAL_Driver/Inc/Legacy
    -Ipedals-module-bootloader-sw/Drivers/CMSIS/Device/ST/STM32C0xx/Include

lib_deps = https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
