/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: pedals_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-03-20 19:46:13 +0100
Generated from: fsm.dot
The finite state machine has:
  4 states
  0 transition functions

******************************************************************************/

#include "fsm.h"
#include "eagletrt-api.h"

#include "throttle-api.h"
#include "brake-api.h"
#include "bots-api.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *state_names[] = { "init", "idle", "error", "flash" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
    do_init,  // in state init
    do_idle,  // in state idle
    do_error, // in state error
    do_flash, // in state flash
};
// No transition functions

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_ERROR
state_t do_init(state_data_t *data) {
    state_t next_state = STATE_IDLE;
    /* Your Code Here */

    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case STATE_IDLE:
        case STATE_ERROR:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FLASH, STATE_ERROR
state_t do_idle(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    EAGLETRT_API_UNUSED(data);

    float throttle = throttle_get_travel_percentage();
    float brake = brake_get_travel_percentage();
    float front_brake_pressure = brake_get_front_pressure();
    float rear_brake_pressure = brake_get_rear_pressure();

    bool is_throttle_bad = throttle_is_throttle_bad();
    bool is_bots_activated = bots_is_bots_triggered();

    EAGLETRT_API_UNUSED(throttle);
    EAGLETRT_API_UNUSED(brake);
    EAGLETRT_API_UNUSED(front_brake_pressure);
    EAGLETRT_API_UNUSED(rear_brake_pressure);
    EAGLETRT_API_UNUSED(is_throttle_bad);
    EAGLETRT_API_UNUSED(is_bots_activated);

    // based on the frequency, send the data
    // here below an example of how it would look like
    // Struct ErrorMessage error;
    // if(is_throttle_bad) error_add_throttle_error(&error)
    // if(is_bots_activated) error_add_bots_error(&error)
    // if(error_is_not_empty(&error)) PAL_send_message(&error)
    //
    // if(enough time for throttle message passed) PAL_send_message(&throttle)
    // if(enough time for brake message passed) PAL_send_message(&brake)
    // if(enough time for brake pressure message passed) PAL_send_message(&front_brake_pressure,&rear_brake_pressure)

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_FLASH:
        case STATE_ERROR:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state error
// valid return states: NO_CHANGE, STATE_ERROR
state_t do_error(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_ERROR:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FLASH, STATE_ERROR
state_t do_flash(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */

    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_FLASH:
        case STATE_ERROR:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

state_t run_state(state_t cur_state, state_data_t *data) {
    state_t new_state = state_table[cur_state](data);
    if (new_state == NO_CHANGE)
        new_state = cur_state;

    return new_state;
}

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    state_t cur_state = STATE_INIT;

    do {
        cur_state = run_state(cur_state, NULL);
        sleep(1);

    } while (1);

    return 0;
}
#endif
