/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: pedals_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2025-09-21 20:56:22 +0200
Generated from: fsm.dot
The finite state machine has:
  5 states
  3 transition functions

******************************************************************************/

#include "fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *state_names[] = {"init", "idle", "error", "flash", "pause"};

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
  do_init,  // in state init
  do_idle,  // in state idle
  do_error, // in state error
  do_flash, // in state flash
  do_pause, // in state pause
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
  /* states:     init           , idle           , error          , flash          , pause           */
  /* init    */ {NULL           , init_completed , NULL           , NULL           , NULL           }, 
  /* idle    */ {NULL           , NULL           , NULL           , initiate_flash , save_parameters}, 
  /* error   */ {NULL           , NULL           , NULL           , NULL           , NULL           }, 
  /* flash   */ {NULL           , NULL           , NULL           , NULL           , NULL           }, 
  /* pause   */ {NULL           , NULL           , NULL           , NULL           , NULL           }, 
};

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_ERROR
state_t do_init(state_data_t *data) {
  state_t next_state = STATE_IDLE;
  /* Your Code Here */
  
  switch (next_state) {
  case STATE_IDLE:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FLASH, STATE_PAUSE, STATE_ERROR
state_t do_idle(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_IDLE:
  case STATE_FLASH:
  case STATE_PAUSE:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state error
// valid return states: NO_CHANGE, STATE_ERROR
state_t do_error(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FLASH, STATE_ERROR
state_t do_flash(state_data_t *data) {
  state_t next_state = NO_CHANGE;
  /* Your Code Here */
  
  switch (next_state) {
  case NO_CHANGE:
  case STATE_IDLE:
  case STATE_FLASH:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}


// Function to be executed in state pause
// valid return states: STATE_IDLE, STATE_ERROR
state_t do_pause(state_data_t *data) {
  state_t next_state = STATE_IDLE;
  /* Your Code Here */
  
  switch (next_state) {
  case STATE_IDLE:
  case STATE_ERROR:
    break;
  default:
    next_state = NO_CHANGE;
  }

  return next_state;
}



/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */    
                                          
// This function is called in 1 transition:
// 1. from init to idle
void init_completed(state_data_t *data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from idle to flash
void initiate_flash(state_data_t *data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from idle to pause
void save_parameters(state_data_t *data) {
  /* Your Code Here */
}


/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

state_t run_state(state_t cur_state, state_data_t *data) {
  state_t new_state = state_table[cur_state](data);
  if (new_state == NO_CHANGE) new_state = cur_state;

  transition_func_t *transition = transition_table[cur_state][new_state];
  if (transition)
    transition(data);

  return new_state;
};



#ifdef TEST_MAIN
#include <unistd.h>
int main() {
  state_t cur_state = STATE_INIT;

  do {
    cur_state = run_state(cur_state, NULL);
    sleep(1);

  } while (1);

  return 0;
}
#endif

