#ifndef BRAKE_H
#define BRAKE_H

//TODO use correct values
#define BRAKE_BPPS_MIN_VALUE 0
#define BRAKE_BPPS_MAX_VALUE 1000

//TODO use correct values
#define BRAKE_BSPS_F_CONVERSION_VALUE (30.0F)
#define BRAKE_BSPS_R_CONVERSION_VALUE (40.0F)

enum BrakeErrorStatus{
	BRAKE_ERROR_STATUS_NO_ERROR,
	BRAKE_ERROR_STATUS_VALUE_OUTSIDE_RANGE,
	BRAKE_ERROR_STATUS_CALLBACK_FAILURE
};

#endif //BRAKE_H