/******************************************************************************
Finite State Machine
Project: fsm.dot
Description: pedals_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-03-20 19:46:13 +0100
Generated from: fsm.dot
The finite state machine has:
  4 states
  0 transition functions

******************************************************************************/

#ifndef FSM_H
#define FSM_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void state_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    STATE_INIT = 0,
    STATE_IDLE,
    STATE_ERROR,
    STATE_FLASH,
    NUM_STATES,
    NO_CHANGE
} state_t;

// State human-readable names
extern const char *state_names[];

// State function prototype
typedef state_t state_func_t(state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_ERROR
state_t do_init(state_data_t *data);
// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FLASH, STATE_ERROR
state_t do_idle(state_data_t *data);
// Function to be executed in state error
// valid return states: NO_CHANGE, STATE_ERROR
state_t do_error(state_data_t *data);
// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FLASH, STATE_ERROR
state_t do_flash(state_data_t *data);

// List of state functions
extern state_func_t *const state_table[NUM_STATES];

// No transition functions

// state manager
state_t run_state(state_t cur_state, state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // FSM_H
