#ifndef THROTTLE_H
#define THROTTLE_H

#define APPS_1_MIN_VALUE 100
#define APPS_1_MAX_VALUE 1100
#define APPS_2_MIN_VALUE 1000
#define APPS_2_MAX_VALUE 2000
#define APPS_3_MIN_VALUE 2000
#define APPS_3_MAX_VALUE 3000

#define APPS_IMPLAUSIBILITY_PERCENTAGE 0.1
#define APPS_MAX_IMPLAUSIBILITY_TIME 100
#define APPS_EPSILON 0.001

#define APPS_NUMBER 3

enum ThrottleStatus {
	THROTTLE_STATUS_OK,
	THROTTLE_STATUS_INSTABLE,
	THROTTLE_STATUS_BAD
};

#endif //THROTTLE_H