#ifndef ADC_CONVERSION_H
#define ADC_CONVERSION_H

#define ADC_CONV_12BIT_TO_VOLT (3.3f / 4095.0f)
#define ADC_CONV_COMMON_DIVIDER (18.0f / (11.8f + 18.0f))
#define ADC_CONV_BOTS_DIVIDER (47.0f / (330.0f + 47.0f))
#define ADC_CONV_BSPS_FRONT_CALIBRATION (1.005f)
#define ADC_CONV_BSPS_REAR_CALIBRATION (1.006f)
#define ADC_CONV_BSPS_MAX_BAR (100.0f)
#define ADC_CONV_BSPS_MIN_BAR (0.0f)

#define ADC_CONV_APPS1_HIGHER_LIMIT (5.0f)
#define ADC_CONV_APPS1_LOWER_LIMIT (3.47f)
#define ADC_CONV_APPS2_HIGHER_LIMIT (3.0f)
#define ADC_CONV_APPS2_LOWER_LIMIT (1.36f)
#define ADC_CONV_APPS3_HIGHER_LIMIT (0.0f)
#define ADC_CONV_APPS3_LOWER_LIMIT (0.0f)
#define ADC_CONV_BPPS_HIGHER_LIMIT (3.7f)
#define ADC_CONV_BPPS_LOWER_LIMIT (2.6f)
#define ADC_CONV_BSPS_HIGHER_LIMIT (4.5f)
#define ADC_CONV_BSPS_LOWER_LIMIT (0.5f)

#define ADC_CONV_SENSE_5V_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_COMMON_DIVIDER))
#define ADC_CONV_BSPS_FRONT_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_COMMON_DIVIDER * ADC_CONV_BSPS_FRONT_CALIBRATION))
#define ADC_CONV_BSPS_REAR_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_COMMON_DIVIDER * ADC_CONV_BSPS_REAR_CALIBRATION))
#define ADC_CONV_BOTS_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_BOTS_DIVIDER))
#define ADC_CONV_BPPS_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_COMMON_DIVIDER))
#define ADC_CONV_APPS_1_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_COMMON_DIVIDER))
#define ADC_CONV_APPS_2_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_COMMON_DIVIDER))
#define ADC_CONV_APPS_3_RAW2VOLT(raw) ((raw) * (ADC_CONV_12BIT_TO_VOLT / ADC_CONV_COMMON_DIVIDER))

#define ADC_CONV_APPS1_NORMALIZE(voltage) (((voltage) - ADC_CONV_APPS1_LOWER_LIMIT) * (1 / (ADC_CONV_APPS1_HIGHER_LIMIT - ADC_CONV_APPS1_LOWER_LIMIT)))
#define ADC_CONV_APPS2_NORMALIZE(voltage) (((voltage) - ADC_CONV_APPS2_LOWER_LIMIT) * (1 / (ADC_CONV_APPS2_HIGHER_LIMIT - ADC_CONV_APPS2_LOWER_LIMIT)))
#define ADC_CONV_APPS3_NORMALIZE(voltage) (((voltage) - ADC_CONV_APPS3_LOWER_LIMIT) * (1 / (ADC_CONV_APPS3_HIGHER_LIMIT - ADC_CONV_APPS3_LOWER_LIMIT)))
#define ADC_CONV_BPPS_NORMALIZE(voltage) (((voltage) - ADC_CONV_BPPS_LOWER_LIMIT) * (1 / (ADC_CONV_BPPS_HIGHER_LIMIT - ADC_CONV_BPPS_LOWER_LIMIT)))
#endif // ADC_CONVERSION_H
